name: Print Text from hellome.html

on:
  push:
    branches:
      - main
jobs:
  print-text:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/set-up@v2
      with: 
        node-version: '14'
      
